apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: redis-deployment
  name: redis-deployment
  namespace: mynamespace
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
     app: redis-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: redis-deployment
    spec:
      containers:
      - name: redisdgess
        image: redis
        imagePullPolicy: Never
        ports:
        - name: redisport
          containerPort: 7000
          protocol: TCP
