apiversion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 4
  selector:
    matchlables:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: k8-demo
        image: arjunachari12/k8s-demo
        ports:
          - name: nodejs-port
              containerPort: 3000
